import type { Task } from "./types/Task";

export const tasks: Task[] = [
  { Phase: "Phase 1", Step: "Step 1", Task: "Design UI", Value: 5, Assignee: "Alice", Deadline: "2025-06-21", Status: "Pending" },
  { Phase: "Phase 1", Step: "Step 2", Task: "Design Wireframes", Value: 8, Assignee: "Bob", Deadline: "2025-07-01", Status: "In Progress" },
  { Phase: "Phase 1", Step: "Step 3", Task: "Create Style Guide", Value: 6, Assignee: "Charlie", Deadline: "2025-07-10", Status: "Completed" },
  { Phase: "Phase 1", Step: "Step 1", Task: "Setup Repo", Value: 3, Assignee: "Dave", Deadline: "2025-06-22", Status: "Completed" },
  { Phase: "Phase 1", Step: "Step 2", Task: "Configure Linter", Value: 4, Assignee: "Eve", Deadline: "2025-06-24", Status: "Pending" },
  { Phase: "Phase 2", Step: "Step 1", Task: "Implement GroupBy", Value: 8, Assignee: "Frank", Deadline: "2025-06-25", Status: "In Progress" },
  { Phase: "Phase 2", Step: "Step 2", Task: "Write Tests", Value: 6, Assignee: "Grace", Deadline: "2025-06-28", Status: "In Progress" },
  { Phase: "Phase 2", Step: "Step 3", Task: "Fix Bugs", Value: 5, Assignee: "Heidi", Deadline: "2025-07-03", Status: "Pending" },
  { Phase: "Phase 2", Step: "Step 1", Task: "Implement Auth", Value: 10, Assignee: "Ivan", Deadline: "2025-07-05", Status: "Completed" },
  { Phase: "Phase 3", Step: "Step 1", Task: "Setup Database", Value: 7, Assignee: "Judy", Deadline: "2025-07-07", Status: "In Progress" },
  { Phase: "Phase 3", Step: "Step 2", Task: "Create ER Diagram", Value: 4, Assignee: "Mallory", Deadline: "2025-07-10", Status: "Pending" },
  { Phase: "Phase 3", Step: "Step 3", Task: "Seed Data", Value: 5, Assignee: "Niaj", Deadline: "2025-07-12", Status: "Completed" },
  { Phase: "Phase 4", Step: "Step 1", Task: "API Design", Value: 8, Assignee: "Olivia", Deadline: "2025-07-14", Status: "Pending" },
  { Phase: "Phase 4", Step: "Step 2", Task: "Implement Endpoints", Value: 9, Assignee: "Peggy", Deadline: "2025-07-16", Status: "In Progress" },
  { Phase: "Phase 4", Step: "Step 3", Task: "Test Endpoints", Value: 7, Assignee: "Quentin", Deadline: "2025-07-18", Status: "Completed" },
  { Phase: "Phase 5", Step: "Step 1", Task: "Integrate Frontend", Value: 9, Assignee: "Rita", Deadline: "2025-07-20", Status: "Pending" },
  { Phase: "Phase 5", Step: "Step 2", Task: "Implement Redux", Value: 6, Assignee: "Steve", Deadline: "2025-07-22", Status: "In Progress" },
  { Phase: "Phase 5", Step: "Step 3", Task: "UI Bug Fixes", Value: 5, Assignee: "Trent", Deadline: "2025-07-24", Status: "Completed" },
  { Phase: "Phase 6", Step: "Step 1", Task: "Setup CI/CD", Value: 8, Assignee: "Uma", Deadline: "2025-07-26", Status: "In Progress" },
  { Phase: "Phase 6", Step: "Step 2", Task: "Add GitHub Actions", Value: 7, Assignee: "Victor", Deadline: "2025-07-28", Status: "Completed" },
  { Phase: "Phase 6", Step: "Step 3", Task: "Deploy to Production", Value: 10, Assignee: "Wendy", Deadline: "2025-07-30", Status: "Pending" },
  { Phase: "Phase 7", Step: "Step 1", Task: "Monitor Logs", Value: 4, Assignee: "Xander", Deadline: "2025-08-02", Status: "In Progress" },
  { Phase: "Phase 7", Step: "Step 2", Task: "Performance Optimization", Value: 9, Assignee: "Yasmine", Deadline: "2025-08-04", Status: "Pending" },
  { Phase: "Phase 7", Step: "Step 3", Task: "Security Audit", Value: 7, Assignee: "Zach", Deadline: "2025-08-06", Status: "Completed" },
  { Phase: "Phase 8", Step: "Step 1", Task: "Final QA", Value: 10, Assignee: "Alice", Deadline: "2025-08-08", Status: "In Progress" },
  { Phase: "Phase 8", Step: "Step 2", Task: "Client Feedback", Value: 6, Assignee: "Bob", Deadline: "2025-08-10", Status: "Pending" },
  { Phase: "Phase 8", Step: "Step 3", Task: "Final Fixes", Value: 7, Assignee: "Charlie", Deadline: "2025-08-12", Status: "Completed" },
  { Phase: "Phase 9", Step: "Step 1", Task: "Prepare Docs", Value: 5, Assignee: "Dave", Deadline: "2025-08-14", Status: "Pending" },
  { Phase: "Phase 9", Step: "Step 2", Task: "Publish Docs", Value: 4, Assignee: "Eve", Deadline: "2025-08-16", Status: "In Progress" },
  { Phase: "Phase 9", Step: "Step 3", Task: "Team Demo", Value: 6, Assignee: "Frank", Deadline: "2025-08-18", Status: "Completed" },
  { Phase: "Phase 10", Step: "Step 1", Task: "Launch Day Prep", Value: 9, Assignee: "Grace", Deadline: "2025-08-20", Status: "Pending" },
  { Phase: "Phase 10", Step: "Step 2", Task: "Marketing Email", Value: 5, Assignee: "Heidi", Deadline: "2025-08-22", Status: "In Progress" },
  { Phase: "Phase 10", Step: "Step 3", Task: "Launch!", Value: 10, Assignee: "Ivan", Deadline: "2025-08-24", Status: "Completed" },
  { Phase: "Phase 1", Step: "Step 2", Task: "Prototype UI", Value: 6, Assignee: "Zoe", Deadline: "2025-06-23", Status: "Completed" },
  { Phase: "Phase 2", Step: "Step 3", Task: "Refactor Code", Value: 7, Assignee: "Alice", Deadline: "2025-06-30", Status: "Pending" },
  { Phase: "Phase 3", Step: "Step 1", Task: "Add Logging", Value: 3, Assignee: "Bob", Deadline: "2025-07-02", Status: "Completed" },
  { Phase: "Phase 4", Step: "Step 2", Task: "Setup WebSocket", Value: 8, Assignee: "Charlie", Deadline: "2025-07-11", Status: "In Progress" },
  { Phase: "Phase 5", Step: "Step 1", Task: "Toast Notifications", Value: 4, Assignee: "Dave", Deadline: "2025-07-13", Status: "Pending" },
  { Phase: "Phase 6", Step: "Step 3", Task: "Payment Gateway", Value: 9, Assignee: "Eve", Deadline: "2025-07-27", Status: "Completed" },
  { Phase: "Phase 7", Step: "Step 1", Task: "Docker Setup", Value: 5, Assignee: "Frank", Deadline: "2025-07-29", Status: "In Progress" },
  { Phase: "Phase 8", Step: "Step 2", Task: "Kubernetes Config", Value: 8, Assignee: "Grace", Deadline: "2025-08-01", Status: "Pending" },
  { Phase: "Phase 9", Step: "Step 3", Task: "Analytics Dashboard", Value: 7, Assignee: "Heidi", Deadline: "2025-08-05", Status: "Completed" },
  { Phase: "Phase 10", Step: "Step 1", Task: "Dark Mode Toggle", Value: 4, Assignee: "Ivan", Deadline: "2025-08-07", Status: "In Progress" },
  { Phase: "Phase 1", Step: "Step 3", Task: "Accessibility Audit", Value: 5, Assignee: "Judy", Deadline: "2025-06-26", Status: "Pending" },
  { Phase: "Phase 2", Step: "Step 1", Task: "Onboarding Flow", Value: 6, Assignee: "Mallory", Deadline: "2025-06-29", Status: "Completed" },
  { Phase: "Phase 3", Step: "Step 2", Task: "Localization", Value: 7, Assignee: "Niaj", Deadline: "2025-07-04", Status: "In Progress" },
  { Phase: "Phase 4", Step: "Step 3", Task: "Mobile Responsiveness", Value: 6, Assignee: "Olivia", Deadline: "2025-07-06", Status: "Completed" },
  { Phase: "Phase 5", Step: "Step 2", Task: "404 Page Design", Value: 3, Assignee: "Peggy", Deadline: "2025-07-09", Status: "Pending" },
  { Phase: "Phase 6", Step: "Step 1", Task: "Skeleton Loaders", Value: 4, Assignee: "Quentin", Deadline: "2025-07-15", Status: "In Progress" }
];
